### ISSUE TITLE
Typo in the metadata

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/indigo-design-docfx#169]
https://github.com/IgniteUI/indigo-design-docfx/blob/master/en/prototyping/interaction-options.md

Read the description metadata.

Find out about **hotpots**, user action, navigation, and transitions

I think this should be hotspots?  Hotpot is a type of restaurant where you cook your own food in a broth at the table.  Mmm...

**Comment by StefanIvanov** [comment]
Is this issue fixed, it seems like an easy fix?

**Comment by ig-ealbert** [comment]
No, this is not fixed yet.

**Comment by ig-ealbert** [comment]
@StefanIvanov Since we need to rebuild anyway, should I just fix this quickly?  It's really easy, but I don't "own" this content.  I guess since it's an improvement, it's ok?

**Comment by StefanIvanov** [comment]
Yes please
