### ISSUE TITLE
YML files cannot contain reserved characters

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/indigo-design-docfx#173]
https://github.com/IgniteUI/indigo-design-docfx/blob/master/en/sidebar-toc/toc.yml
I'm pretty sure that the `&` symbol is reserved in YML.  Using it will break the TOC.

**Comment by StefanIvanov** [comment]
why not update the TOC to say Prototyping and Usability Studies?

**Comment by ig-ealbert** [comment]
Fixed in #175.  The getting-started page was renamed to getting-started-alt which is why I was not seeing the TOC on staging.
