### ISSUE TITLE
Unsuccessfull attempt at italicizing a string

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/indigo-design-docfx#191]
1. Open https://jp.staging.infragistics.local/products/indigo-design/help/codegen/layout-codegen.html
2. Find the string コード生成から_一貫性のあるレイアウト_
3. Examine the string.

The _ _ should italicize the text but in this situation it's not for some reason (maybe space is needed before anfter the _ _).

**Comment by StefanIvanov** [comment]
Actually *text* makes it Italics but it gets automatically transformed in the underscores can you test with asterisk chars instead of underscores

**Comment by ig-ealbert** [comment]
I'll look into this today.  However, we shouldn't be italicizing Japanese text as it becomes very difficult to read.

**Comment by StefanIvanov** [comment]
closed with #193
