### ISSUE TITLE
Unnecessary 。

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/indigo-design-docfx#200]
1. Open https://jp.staging.infragistics.local/products/indigo-design/help/components/grid.html
2. Search for 複数行の選択が可能にする最初の列のテンプレート。) あります。
The first 。is unnecessary.

Really minor issue. I'm fine if it stays.

**Comment by ig-ealbert** [comment]
@yoshimis added this during her review, so I assume it was intentional.  I will leave it as-is.  Please let me know if I can close this issue.
#199

**Comment by ig-ealbert** [comment]
@yoshimis Do you want to create a pull request for this change?

**Comment by yoshimis** [comment]
Created. #206.
