### ISSUE TITLE
Adding Shadow step is missing or irrelevant sentences exist in creating-an-artboard.md

### ISSUE THREAD

**Issue by DaizenIG** [IgniteUI/indigo-design-docfx#207]
Step to reproduce:

1. Open [creating-an-artboard.md](https://github.com/IgniteUI/indigo-design-docfx/blob/master/en/creating-an-artboard.md)
2. Navigate to "Add the background for the form."

Actual Result:
From the Insert menu, select Colors/white to add the rectangle. **Make it the same size as the shadow and align them.**
**Select both layers. Set their size to 280 by 400.**

Expected Result:
There is no instruction to add shadow, If readers follow instruction, only Color/white is added.

**Comment by StefanIvanov** [comment]
We have removed the step of adding a shadow because code gen does not support shadows yet.

**Comment by ig-ealbert** [comment]
I think Daizen means that the instructions to "Make it the same size as the shadow and align them.  Select both layers.  Set their size to 280 by 400." doesn't make sense if there is no shadow.

**Comment by DaizenIG** [comment]
yes, that's what I meant. Thanks @ig-ealbert. if the step is no longer needed, I wanted docs to be updated accordingly. Thanks for updaing @StefanIvanov
