### ISSUE TITLE
Missing warning in the calendar topic

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/indigo-design-docfx#219]
1. Open https://staging.infragistics.local/products/indigo-design/help/components/calendar.html
2. Search for "WARNING", the only warning in the topic.
3. Open https://jp.staging.infragistics.local/products/indigo-design/help/components/calendar.html
4. Try to find the warning.

It's not there, it's missing from the md file as well ;(

**Comment by ig-ealbert** [comment]
@valadzhov I intentionally left this section out of the Japanese topic.  You can see that the entire Code Generation section is just a placeholder in English.  I think it's better to have nothing there than to have a placeholder.  I will add it once the code generation is ready for the Calendar.  If you'd like to learn more about when the code generation will be ready, I'd recommend checking with Stefan.
Please close this issue if you agree, or reassign to Stefan if you think that this should remain open until the control code generation is ready.

**Comment by StefanIvanov** [comment]
The warning will be valid after the component is able to generate code, but the whole section will expand with the details of the process

**Comment by valadzhov** [comment]
I agree, closing the issue!
