### ISSUE TITLE
Image references weren't removed after the images were deleted.

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/indigo-design-docfx#222]
1. Open https://jp.staging.infragistics.local/products/indigo-design/help/patterns/form.html
2. Find "登録フォームは簡易なコンテンツおよび操作を持つレイアウトがあり、またはより複雑なレイアウトと追加の操作を持つソーシャル メディア プロファイルの登録フォームがあります。"
3. Examine the space below that string.

There are missing image icons. This is happening in EN as well.

**Comment by ig-ealbert** [comment]
@StefanIvanov Should I remove these images in both EN or JP, or is there something else we should do to resolve this issue?  Ex. restore the images, or remove some text along with the images?

**Comment by ig-ealbert** [comment]
form_register-simple and form_register-social

**Comment by StefanIvanov** [comment]
it runs locally for me but I also see the missing image icons on staging. Could it be a bug with the staging version, because I see the images among the files on GitHub as well?

**Comment by ig-ealbert** [comment]
@StefanIvanov The files are named with "copy".  That's the problem.
![image](https://user-images.githubusercontent.com/8162597/44348083-7e28f400-a467-11e8-9d50-e6f729acf96e.png)
