### ISSUE TITLE
Creating Responsive Layouts video is not working

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/indigo-design-docfx#226]
http://infragistics.com/indigo-docfx/video-tutorials.html
Check the "Creating Responsive Layouts" video.
It is not working.  Reported by @DaizenIG.

**Comment by StefanIvanov** [comment]
We should assign someone to check the issue, who has worked on the page and is most familiar with it? Could it be Pat?

**Comment by ig-ealbert** [comment]
I just spoke with George and he says he can get the correct link and submit a pull request.  Otherwise, I can do it if I can be sent the correct video link.

**Comment by ig-ealbert** [comment]
Fixed on production now.
