### ISSUE TITLE
(EN/JP) Link is broken on codegen/data-binding.md

### ISSUE THREAD

**Issue by DaizenIG** [IgniteUI/indigo-design-docfx#247]
Step to reproduce

1. Open either one of help pages:
EN -https://jp.infragistics.com/products/indigo-design/help/codegen/data-binding.html
JP - https://www.infragistics.com/products/indigo-design/help/codegen/data-binding.html

2. Scroll to the page end and click Indigo.Design Code Generator link

Expected result:
link should be working

Actual Result:
Both links are borken

**Comment by StefanIvanov** [comment]
@ig-robstoffers , where should this link point to? And do we need to have a link at all there?

**Comment by ig-robstoffers** [comment]
I think it should go here: https://www.infragistics.com/products/indigo-design/help/codegen/vscode-plugin.html

**Comment by StefanIvanov** [comment]
#248 has the fix
