### ISSUE TITLE
Images x2 size render double

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/indigo-design-docfx#25]
We export images from Sketch at x2 resolution to make sure that they are crisp on retina display, but in the browser they are rendered in an image with double the size that the intended one.

**Comment by StefanIvanov** [comment]
any updates on this issue? ETA?

**Comment by tiliev** [comment]
@StefanIvanov, let's prepare the images and later I'll add a script to complete the task. So please do the following things:
1. Rename all the images to `name@2x.png`. Basically append `@2x` to the name of each image.
2. Export all of the images again but to their normal sizes. They'll have the names which you currently have.
3. Each image in the website should be changed from ` ![](../images/card_custom_layout0.png)` to `<img class="retina-image" src="../images/card_custom_layout0.png">`. This will render the images with their true size.

Note: Please apply these changes to the "EN" as well as "JP" versions of the site.

Later I'll add a script which will detect the device scale and change the "src" of the images to 2x if needed.
