### ISSUE TITLE
Images are not responsive.

### ISSUE THREAD

**Issue by cbadell** [IgniteUI/indigo-design-docfx#266]
1. Enter to [www.infragistics.com/products/indigo-design/help](https://www.infragistics.com/products/indigo-design/help)
2. Enter to any topic which contains at least one image. E.g. [www.infragistics.com/products/indigo-design/help/codegen/installing-vs-code-extension.html](https://www.infragistics.com/products/indigo-design/help/codegen/installing-vs-code-extension.html)
3. Resize browser to a small size.

Result: image is clipped instead of fitting it to the width of the display area.

Obtained:
![image](https://user-images.githubusercontent.com/17707711/53173314-3033ab00-35c6-11e9-9cf4-c3cef26f9cf0.png)

Image content:
![image](https://user-images.githubusercontent.com/17707711/53173343-3b86d680-35c6-11e9-86dd-3c691f1523de.png)

**Comment by cbadell** [comment]
Pablo noticed that setting `max-width: 100% ` for images at the css file makes all images responsive. I think it worth to fix it at igniteui-docfx-template. Submitted [here](https://github.com/IgniteUI/indigo-design-docfx/issues/266) the issue.

**Comment by zdrawku** [comment]
Hey Claudia, the fix seems reasonable, I am going to talk with @StefanIvanov who is going to work on that issue from our side

**Comment by cbadell** [comment]
Great! Thanks!

**Comment by tiliev** [comment]
@cbadell, we'll need to add a CSS class to all images and apply a style for responsiveness, e.g. `max-width: 100%`. This will take time but we'll do it. I'll keep you posted.

**Comment by cbadell** [comment]
@tiliev let me know if I can help adding that setting. Maybe we can split the topics between us.

**Comment by Aleksandyr** [comment]
We need to apply that particular class to some further images that was missed be accident.

- [https://staging.infragistics.local/products/indigo-design/help/prototyping/interaction-options.html](https://staging.infragistics.local/products/indigo-design/help/prototyping/interaction-options.html)
- interaction_options_1.png

- [https://staging.infragistics.local/products/indigo-design/help/codegen/vscode-plugin.html](https://staging.infragistics.local/products/indigo-design/help/codegen/vscode-plugin.html)
- step1.gif
- chrome.png
- step2.gif

- [https://jp.staging.infragistics.local/products/indigo-design/help/codegen/vscode-plugin.html]( https://jp.staging.infragistics.local/products/indigo-design/help/codegen/vscode-plugin.html)
- step1.gif
- chrome.png
- step2.gif
