### ISSUE TITLE
Update Indigo Design docfx TOC

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/indigo-design-docfx#328]
Update the [Indigo Design docfx TOC](https://www.infragistics.com/products/indigo-design/help/getting-started.html) with the template used for the Ignite UI Angular

**Comment by dobromirts** [comment]
Indigo Design changes
- [ ] Update template version
- [ ] Generate sitemap.xml
- [ ] Remove all .html from sitemap
- [ ] Remove .html from URL - check all rewrite rules
- [ ] Remove .html from internal links part of all topics
- [ ] Remove all .html from TOC
- [ ] Structure review of all topics

**Comment by zdrawku** [comment]
Everything is working fine - https://staging.infragistics.com/indigo-docfx/getting-started
