### ISSUE TITLE
Indigo.Design App Builder components

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/indigo-design-docfx#358]
Create [Indigo.Design App Builder components](https://staging.infragistics.com/products/indigo-design/help/appbuilder/indigo.design-app-builder-components.html) parent topic.

**Comment by DaniMarinov** [comment]
Link to the completed documentation 
https://www.infragistics.com/products/indigo-design/help/appbuilder/indigo-design-app-builder-components
