### ISSUE TITLE
Using Data in Your App

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/indigo-design-docfx#373]
Update [Using Data in Your App ](https://staging.infragistics.com/products/indigo-design/help/appbuilder/using-data-in-your-app.html)

**Comment by DaniMarinov** [comment]
I will update this once the Data Source feature is implemented

**Comment by StefanIvanov** [comment]
@radomirchev @DaniMarinov  I think you can close this one, it seems like it has been long resolved

**Comment by DaniMarinov** [comment]
yes, it is.
