### ISSUE TITLE
Rename "File Upload" page in Sketch

### ISSUE THREAD

**Issue by YoannaIvanova** [IgniteUI/indigo-design-docfx#472]
Rename "File Upload" page in Sketch to "File Upload+Image Manipulation".

<img width="632" alt="Screenshot 2021-02-08 at 10 57 12" src="https://user-images.githubusercontent.com/61508933/107941051-cf12f800-6f91-11eb-8d3c-38738172a9b7.png">
<img width="916" alt="Screenshot 2021-02-08 at 10 57 26" src="https://user-images.githubusercontent.com/61508933/107941066-d0dcbb80-6f91-11eb-8cec-5ac9df99d209.png">

**Comment by StefanIvanov** [comment]
https://share.goabstract.com/2306bd8f-e8f0-487b-bf33-5dac026a32a6
