### ISSUE TITLE
Move App Builder topics into new app/url

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/indigo-design-docfx#576]
These are the topics that have to be moved to a different docfx instance

![image](https://user-images.githubusercontent.com/11193764/140526544-5fe8e2c5-5d3d-4fa1-b1de-392f6cf7b3a9.png)

Lets add it under the URL www.infragistics.com/products/appbuilder/docs

**Comment by hanastasov** [comment]
Make sure sitemap xml is available in the files.
