### ISSUE TITLE
Meta-description - Keywords - Content Edits

### ISSUE THREAD

**Issue by a-bildungSROMAN** [IgniteUI/indigo-design-docfx#66]
Design Systems, Design Systems UX, UI kit, Sketch, Ignite UI for Angular, Sketch to Angular, Sketch to Angular, Angular, Angular Design System, Export code from Sketch, Design Kits for Angular, Sketch HTML, Sketch to HTML, Sketch UI kits

**Comment by StefanIvanov** [comment]
Is this supposed to go in all the topics, or just in the patterns topics?

**Comment by a-bildungSROMAN** [comment]
I was thinking all topics, unless you want individual items to have specifically tailored keywords?
