### ISSUE TITLE
All steps are 1.

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/indigo-design-docfx#77]
http://staging.infragistics.local/indigo-docfx/components/cards-custom.html

Check the steps.  They are all numbered 1.  They should be in increasing numbers.  Or not ordered (ex. `*` or just paragraphs).

**Comment by StefanIvanov** [comment]
I also see this for the EN
Is it possible that the   <div class="divider--half"></div> we use to space out the screenshots are causing this weird behavior?

**Comment by ig-ealbert** [comment]
I think all numbered list items need to be direct siblings of each other.
Ex.
1. One
2. Two
3. Three
In AsciiDoc we have some way of specifying the number to use, but I don't think that exists in Markdown.

**Comment by ig-ealbert** [comment]
I seem to have fixed this by indenting anything between list items by 2 spaces.  Check my linked commit.  There are other topics where this happens too, and I think I've fixed them in Japanese.  The same workaround should be applicable in English.

**Comment by tiliev** [comment]
@ig-ealbert, yes this is the fix. @StefanIvanov, please apply the fix where needed.
