### ISSUE TITLE
Badge Content Edits

### ISSUE THREAD

**Issue by a-bildungSROMAN** [IgniteUI/indigo-design-docfx#8]
Use the Badge Component to draw attention to another interface element or to display a notification. It enhances the component to which it is attached with additional information, disclosed to the user upon interacting with it. The Badge is visually identical to the [Ignite UI for Angular Badge Component](https://www.infragistics.com/products/ignite-ui-angular/angular/components/badge.html).

The Badge comes with styling flexibility through the various overrides controlling the background and border colors, as well as the presence of a shadow that is cast on the underlying interface element. 

Use the Badge to "stamp" another piece of UI, such as an Avatar or a text title and avoid using the Badge on its own.

Our community is active and always welcoming to new ideas.

Indigo Design to Code Studio on GitHub

**Comment by StefanIvanov** [comment]
Sarah do we need to call it Indigo Design to Code Studio, my understanding is that we are using the shorter Indigo Design. Could you please double check with Holly?
