### ISSUE TITLE
Images don't appear even though I added them

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/indigo-design-docfx#86]
https://jp.staging.infragistics.local/indigo-docfx/getting-started.html

Check for images.

They are 404.  I added them and queued a new build.  Why don't they show up?  Do I have to do something else to get them to be copied to the server?

**Comment by tiliev** [comment]
@ig-ealbert, I tested locally and it works. Please test again and let me know. Your latest PR might have fixed them.

**Comment by ig-ealbert** [comment]
@tiliev I still don't see the images.  Check under steps 3+?
If you press F12, do you get the 404 errors?
Do I need to clear my cache or something?  I've tried Ctrl + F5 but they still don't appear.

**Comment by ig-ealbert** [comment]
This is also happening here:
https://jp.staging.infragistics.local/indigo-docfx/patterns/user-profile.html

**Comment by ig-ealbert** [comment]
Fixed in user-profile.html.  However, I still get 404s in the getting-started topic.

**Comment by ig-ealbert** [comment]
Are the root level topics looking in the wrong place?  If so, I may be able to fix that.  This happens in English too so I'm guessing that's the problem.
https://staging.infragistics.local/indigo-docfx/getting-started.html
